# Generated by Django 5.2.7 on 2025-10-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('yard_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guestentries', to='yard_control.yard', verbose_name='двор'),
        ),
    ]
