# Generated by Django 5.2.7 on 2025-10-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Гостя', 'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='guestentry',
            options={'verbose_name': 'Гостевого входа', 'verbose_name_plural': 'Гостевые входы'},
        ),
    ]
