# Generated by Django 5.2.7 on 2025-10-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='enter_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='entry_timeout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
