# Generated by Django 5.2.7 on 2025-10-18 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_guestentry_enter_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestentry',
            options={'verbose_name': 'Гостевой заявки', 'verbose_name_plural': 'Гостевые заявки'},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invite_by',
        ),
        migrations.AddField(
            model_name='guestentry',
            name='invite_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guests', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший'),
        ),
    ]
