# Generated by Django 5.2.7 on 2025-10-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_guestentry_options_remove_guest_invite_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='auto_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='автомобильный номер'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='enter_time',
            field=models.DateTimeField(null=True, verbose_name='время заезда'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='entry_timeout',
            field=models.DateTimeField(null=True, verbose_name='таймаут на въезд'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='out_time',
            field=models.DateTimeField(null=True, verbose_name='время выезда'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='статус админа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
