# Generated by Django 5.2.7 on 2025-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_guest_auto_number_alter_guest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='enter_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время заезда'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='entry_timeout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='таймаут на въезд'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время выезда'),
        ),
    ]
