# Generated by Django 5.2.7 on 2025-10-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_guestentry_enter_time_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
