# Generated by Django 5.2.7 on 2025-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_requester', models.CharField(verbose_name='ФИО запросившего')),
                ('phone', models.CharField(verbose_name='Номер телефона запросифшего')),
                ('org_name', models.CharField(verbose_name='Название организации')),
                ('org_type', models.CharField(verbose_name='Тип организации')),
                ('quantity_objects', models.IntegerField(verbose_name='Количество объектов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки формы')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'db_table': 'demoforms',
            },
        ),
    ]
