# Generated by Django 5.2.7 on 2025-10-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_number', models.CharField(max_length=8, unique=True, verbose_name='автомобильный номер')),
                ('is_confirmed', models.BooleanField(verbose_name='Подтверждена')),
                ('expires_at', models.DateTimeField(verbose_name='Временный доступ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automobiles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобиля',
                'verbose_name_plural': 'Автомобилей',
                'db_table': 'automobiles',
            },
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True, verbose_name='адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_yards', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('users', models.ManyToManyField(blank=True, related_name='yards_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи двора')),
            ],
            options={
                'verbose_name': 'Двора',
                'verbose_name_plural': 'Дворов',
                'db_table': 'yards',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_invites', to=settings.AUTH_USER_MODEL, verbose_name='кто пригласил')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='yard_control.yard', verbose_name='в какой двор приглашение')),
            ],
            options={
                'verbose_name': 'Приглашения',
                'verbose_name_plural': 'Приглашений',
                'db_table': 'invites',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_number', models.CharField(max_length=8, unique=True, verbose_name='автомобильный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='yard_control.yard', verbose_name='черный список двора')),
            ],
            options={
                'verbose_name': 'Черного списка',
                'verbose_name_plural': 'Черных списков',
                'db_table': 'blacklists',
            },
        ),
    ]
