# Generated by Django 5.2.7 on 2025-10-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobile',
            options={'verbose_name': 'Автомобиля', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': 'Черного списка', 'verbose_name_plural': 'Черные списки'},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Приглашения', 'verbose_name_plural': 'Приглашения'},
        ),
        migrations.AlterModelOptions(
            name='yard',
            options={'verbose_name': 'Двора', 'verbose_name_plural': 'Дворы'},
        ),
    ]
