# Generated by Django 5.2.7 on 2025-10-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0002_alter_automobile_options_alter_blacklist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yard_control.automobile', verbose_name='авто')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_history', to='yard_control.yard', verbose_name='какого двора история')),
            ],
            options={
                'verbose_name': 'Истроия въездов',
                'verbose_name_plural': 'Истрории въездов',
                'db_table': 'entryhistories',
            },
        ),
        migrations.CreateModel(
            name='OutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yard_control.automobile', verbose_name='авто')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_history', to='yard_control.yard', verbose_name='какого двора история')),
            ],
            options={
                'verbose_name': 'Истроия выездов',
                'verbose_name_plural': 'Истрории выездов',
                'db_table': 'outhistories',
            },
        ),
    ]
