# Generated by Django 5.2.7 on 2025-10-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0003_entryhistory_outhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='expires_at',
            field=models.DateTimeField(null=True, verbose_name='Временный доступ'),
        ),
    ]
