# Generated by Django 5.2.7 on 2025-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0004_alter_automobile_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
    ]
