# Generated by Django 5.2.7 on 2025-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0005_alter_automobile_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='automobiles',
            field=models.ManyToManyField(blank=True, related_name='yards_auto', to='yard_control.automobile', verbose_name='Машины двора'),
        ),
    ]
