# Generated by Django 5.2.7 on 2025-10-24 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0006_yard_automobiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Гостевое авто'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='auto_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='автомобильный номер'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automobiles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='auto_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='автомобильный номер'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='entryhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата проезда'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='outhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата проезда'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
