# Generated by Django 5.2.7 on 2025-10-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0007_automobile_is_guest_alter_automobile_auto_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Временный доступ'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='yard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_lists', to='yard_control.yard', verbose_name='черный список двора'),
        ),
    ]
