# Generated by Django 5.2.7 on 2025-10-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0008_alter_automobile_expires_at_alter_blacklist_yard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='auto_number',
            field=models.CharField(max_length=9, verbose_name='автомобильный номер'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='yard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yard_control.yard', verbose_name='черный список двора'),
        ),
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('auto_number', 'yard')},
        ),
    ]
