# Generated by Django 5.2.7 on 2025-10-29 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0009_alter_blacklist_auto_number_alter_blacklist_yard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryhistory',
            options={'verbose_name': 'Истроия въездов', 'verbose_name_plural': 'Истории въездов'},
        ),
        migrations.RemoveField(
            model_name='entryhistory',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='outhistory',
            name='auto',
        ),
        migrations.AddField(
            model_name='entryhistory',
            name='auto_number',
            field=models.CharField(max_length=9, null=True, verbose_name='автомобильный номер'),
        ),
        migrations.AddField(
            model_name='outhistory',
            name='auto_number',
            field=models.CharField(max_length=9, null=True, verbose_name='автомобильный номер'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_invites', to=settings.AUTH_USER_MODEL, verbose_name='кого пригласили'),
        ),
    ]
