# Generated by Django 5.2.7 on 2025-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0010_alter_entryhistory_options_remove_entryhistory_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.AddField(
            model_name='invite',
            name='user_phone',
            field=models.CharField(blank=True, verbose_name='Телефон пользователя'),
        ),
    ]
