# Generated by Django 5.2.7 on 2025-11-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0011_remove_invite_user_invite_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmAutoInYard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yard_control.automobile', verbose_name='машина')),
                ('yard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yard_control.yard', verbose_name='двор')),
            ],
        ),
    ]
