# Generated by Django 5.2.7 on 2025-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0012_confirmautoinyard'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmautoinyard',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
    ]
