# Generated by Django 5.2.7 on 2025-11-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0013_confirmautoinyard_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobile',
            name='is_confirmed',
        ),
    ]
