# Generated by Django 5.2.7 on 2025-11-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_control', '0014_remove_automobile_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='yard_control.yard', verbose_name='в какой двор приглашение'),
        ),
    ]
